<RootScreen>

    MDBottomNavigation:

        MDBottomNavigationItem:
            name: "today screen"
            icon: "calendar"
            text: "Today"

            TodayScreen:

        MDBottomNavigationItem:
            name: "all exercieses screen"
            icon: "dumbbell"
            text: "All Exercieses"

            AllExerciesesScreen:

        MDBottomNavigationItem:
            name: "settings screen"
            icon: "cog"
            text: "Settings"
