<LeftBar@MDRelativeLayout>
    size_hint_x: None
    width: "72dp"

    MDCard:
        orientation: "vertical"
        size_hint: None, None
        size: "48dp", "150dp"
        radius: 24
        md_bg_color: app.theme_cls.bg_dark
        pos_hint: {"center_x": .9, "center_y": .5}

        BadgeButton:
            icon: "email"
            text: "10"

        BadgeButton:
            icon: "magnify"

        BadgeButton:
            icon: "bell-ring-outline"
            text: "20"